spring:
  jpa.hibernate.ddl-auto: update
  spring.jpa.hibernate.ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/ejercicio1?createDatabaseIfNotExist=true
    username: root
    password: 123456Aa-
  hikari:
    connection_timeout: 60000
    maximum-pool-size: 5
server:
  port: 8081
logging:
  level: 
    root: INFO
  file:
    name: C:\logs\holaMundo.log
    max-size : 1MB
    max-history: 10
    total-size-cap: 10MB